### ISSUE TITLE
Error No tr064 service found for...

### ISSUE THREAD

**Issue by gitbock** [gitbock/fritzboxtr064#2]
From https://github.com/openhab/openhab/pull/2494#issuecomment-152315713

```
2015-10-28 21:22:56.565 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - FritzboxTr064 executing...
2015-10-28 21:22:56.568 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - No tr064 service found for service id DeviceInfo-com:serviceId:DeviceInfo1
2015-10-28 21:22:56.580 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Error constructing request SOAP msg for getting parameter
2015-10-28 21:22:56.582 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - null
2015-10-28 21:22:56.585 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Request was: modelName
2015-10-28 21:22:56.588 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Could not determine data to be sent to fbox!
2015-10-28 21:22:56.597 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - No tr064 service found for service id LanDeviceHosts-com:serviceId:Hosts1
2015-10-28 21:22:56.616 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Error constructing request SOAP msg for getting parameter
2015-10-28 21:22:56.618 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - null
2015-10-28 21:22:56.621 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Request was: maconline:XX-YY-ZZ-AA-BB-CC
2015-10-28 21:22:56.624 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Could not determine data to be sent to fbox!
2015-10-28 21:22:56.635 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - No tr064 service found for service id urn:WANPPPConnection-com:serviceId:WANPPPConnection1
2015-10-28 21:22:56.650 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Error constructing request SOAP msg for getting parameter
2015-10-28 21:22:56.653 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - null
2015-10-28 21:22:56.656 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Request was: wanip
2015-10-28 21:22:56.659 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Could not determine data to be sent to fbox!

2015-10-28 21:31:04.545 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Error constructing request SOAP msg for getting parameter
2015-10-28 21:31:04.549 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - null
2015-10-28 21:31:04.566 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Request was: modelName
2015-10-28 21:31:04.571 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Could not determine data to be sent to fbox!
2015-10-28 21:31:04.618 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - No tr064 service found for service id LanDeviceHosts-com:serviceId:Hosts1
2015-10-28 21:31:04.634 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Error constructing request SOAP msg for getting parameter
2015-10-28 21:31:04.658 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - null
2015-10-28 21:31:04.666 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Request was: maconline:XX-YY-ZZ-AA-BB-CC
2015-10-28 21:31:04.676 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Could not determine data to be sent to fbox!
2015-10-28 21:31:04.688 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - No tr064 service found for service id urn:WANPPPConnection-com:serviceId:WANPPPConnection1
2015-10-28 21:31:04.703 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Error constructing request SOAP msg for getting parameter
2015-10-28 21:31:04.726 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - null
2015-10-28 21:31:04.738 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Request was: wanip
2015-10-28 21:31:04.746 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - Could not determine data to be sent to fbox!
```

**Comment by gitbock** [comment]
For some reason, the binding cannot read the available services from your fbox. 
1) Double-check if the tr064 is enabled in your fbox:

![screenshot](http://abload.de/img/fbox_tr64skpjj.png)

2) Type the following in your browser and post the output

```
https://fritz.box:49443/tr64desc.xml
```

or

```
https://<ip-of-fritzbox>:49443/tr64desc.xml
```

3) Try the unencrypted one as well

```
http://<ip-of-fritzbox>:49000/tr64desc.xml
```

4) Post your openhab.cfg section for the tr064
**WATCH OUT FOR NOT COPY&PASTE THE PASSWORD :)**

**Comment by dampfnudel** [comment]
```

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<root xmlns="urn:dslforum-org:device-1-0">
    <specVersion>
        <major>1</major>
        <minor>0</minor>
    </specVersion>
    <device>
        <deviceType>urn:dslforum-org:device:InternetGatewayDevice:1</deviceType>
        <friendlyName>FRITZ!Box 6360 Cable (um)</friendlyName>
        <manufacturer>AVM</manufacturer>
        <manufacturerURL>www.avm.de</manufacturerURL>
        <modelDescription>FRITZ!Box 6360 Cable (um)</modelDescription>
        <modelName>FRITZ!Box 6360 Cable (um)</modelName>
        <modelNumber>- unity</modelNumber>
        <modelURL>www.avm.de</modelURL>
        <UDN>uuid:AAAAA</UDN>
        <iconList>
            <icon>
                <mimetype>image/gif</mimetype>
                <width>118</width>
                <height>119</height>
                <depth>8</depth>
                <url>/ligd.gif</url>
            </icon>
        </iconList>
        <serviceList>
            <service>
                <serviceType>urn:dslforum-org:service:DeviceInfo:1</serviceType>
                <serviceId>urn:DeviceInfo-com:serviceId:DeviceInfo1</serviceId>
                <controlURL>/upnp/control/deviceinfo</controlURL>
                <eventSubURL>/upnp/control/deviceinfo</eventSubURL>
                <SCPDURL>/deviceinfoSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:DeviceConfig:1</serviceType>
                <serviceId>urn:DeviceConfig-com:serviceId:DeviceConfig1</serviceId>
                <controlURL>/upnp/control/deviceconfig</controlURL>
                <eventSubURL>/upnp/control/deviceconfig</eventSubURL>
                <SCPDURL>/deviceconfigSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:Layer3Forwarding:1</serviceType>
                <serviceId> urn:Layer3Forwarding-com:serviceId:Layer3Forwarding1 
                </serviceId>
                <controlURL>/upnp/control/layer3forwarding</controlURL>
                <eventSubURL>/upnp/control/layer3forwarding</eventSubURL>
                <SCPDURL>/layer3forwardingSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:LANConfigSecurity:1</serviceType>
                <serviceId> urn:LANConfigSecurity-com:serviceId:LANConfigSecurity1 
                </serviceId>
                <controlURL>/upnp/control/lanconfigsecurity</controlURL>
                <eventSubURL>/upnp/control/lanconfigsecurity</eventSubURL>
                <SCPDURL>/lanconfigsecuritySCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:ManagementServer:1</serviceType>
                <serviceId> urn:ManagementServer-com:serviceId:ManagementServer1 
                </serviceId>
                <controlURL>/upnp/control/mgmsrv</controlURL>
                <eventSubURL>/upnp/control/mgmsrv</eventSubURL>
                <SCPDURL>/mgmsrvSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:Time:1</serviceType>
                <serviceId>urn:Time-com:serviceId:Time1</serviceId>
                <controlURL>/upnp/control/time</controlURL>
                <eventSubURL>/upnp/control/time</eventSubURL>
                <SCPDURL>/timeSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:UserInterface:1</serviceType>
                <serviceId>urn:UserInterface-com:serviceId:UserInterface1</serviceId>
                <controlURL>/upnp/control/userif</controlURL>
                <eventSubURL>/upnp/control/userif</eventSubURL>
                <SCPDURL>/userifSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:X_VoIP:1</serviceType>
                <serviceId>urn:X_VoIP-com:serviceId:X_VoIP1</serviceId>
                <controlURL>/upnp/control/x_voip</controlURL>
                <eventSubURL>/upnp/control/x_voip</eventSubURL>
                <SCPDURL>/x_voipSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:X_AVM-DE_Storage:1</serviceType>
                <serviceId> urn:X_AVM-DE_Storage-com:serviceId:X_AVM-DE_Storage1 
                </serviceId>
                <controlURL>/upnp/control/x_storage</controlURL>
                <eventSubURL>/upnp/control/x_storage</eventSubURL>
                <SCPDURL>/x_storageSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:X_AVM-DE_OnTel:1</serviceType>
                <serviceId>urn:X_AVM-DE_OnTel-com:serviceId:X_AVM-DE_OnTel1</serviceId>
                <controlURL>/upnp/control/x_contact</controlURL>
                <eventSubURL>/upnp/control/x_contact</eventSubURL>
                <SCPDURL>/x_contactSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:X_AVM-DE_WebDAVClient:1</serviceType>
                <serviceId> urn:X_AVM-DE_WebDAV-com:serviceId:X_AVM-DE_WebDAVClient1 
                </serviceId>
                <controlURL>/upnp/control/x_webdav</controlURL>
                <eventSubURL>/upnp/control/x_webdav</eventSubURL>
                <SCPDURL>/x_webdavSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:X_AVM-DE_UPnP:1</serviceType>
                <serviceId>urn:X_AVM-DE_UPnP-com:serviceId:X_AVM-DE_UPnP1</serviceId>
                <controlURL>/upnp/control/x_upnp</controlURL>
                <eventSubURL>/upnp/control/x_upnp</eventSubURL>
                <SCPDURL>/x_upnpSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:X_AVM-DE_RemoteAccess:1</serviceType>
                <serviceId> urn:X_AVM-DE_RemoteAccess-com:serviceId:X_AVM-DE_RemoteAccess1 
                </serviceId>
                <controlURL>/upnp/control/x_remote</controlURL>
                <eventSubURL>/upnp/control/x_remote</eventSubURL>
                <SCPDURL>/x_remoteSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:X_AVM-DE_MyFritz:1</serviceType>
                <serviceId> urn:X_AVM-DE_MyFritz-com:serviceId:X_AVM-DE_MyFritz1 
                </serviceId>
                <controlURL>/upnp/control/x_myfritz</controlURL>
                <eventSubURL>/upnp/control/x_myfritz</eventSubURL>
                <SCPDURL>/x_myfritzSCPD.xml</SCPDURL>
            </service>
            <service>
                <serviceType>urn:dslforum-org:service:X_AVM-DE_TAM:1</serviceType>
                <serviceId>urn:X_AVM-DE_TAM-com:serviceId:X_AVM-DE_TAM1</serviceId>
                <controlURL>/upnp/control/x_tam</controlURL>
                <eventSubURL>/upnp/control/x_tam</eventSubURL>
                <SCPDURL>/x_tamSCPD.xml</SCPDURL>
            </service>
        </serviceList>
        <deviceList>
            <device>
                <deviceType>urn:dslforum-org:device:LANDevice:1</deviceType>
                <friendlyName>LANDevice - FRITZ!Box 6360 Cable (um)</friendlyName>
                <manufacturer>AVM</manufacturer>
                <manufacturerURL>www.avm.de</manufacturerURL>
                <modelDescription>LANDevice - FRITZ!Box 6360 Cable (um)</modelDescription>
                <modelName>LANDevice - FRITZ!Box 6360 Cable (um)</modelName>
                <modelNumber>- unity</modelNumber>
                <modelURL>www.avm.de</modelURL>
                <UDN>uuid:BBBBB</UDN>
                <UPC>AVM TR-064</UPC>
                <serviceList>
                    <service>
                        <serviceType>urn:dslforum-org:service:WLANConfiguration:1</serviceType>
                        <serviceId> urn:WLANConfiguration-com:serviceId:WLANConfiguration1 
                        </serviceId>
                        <controlURL>/upnp/control/wlanconfig1</controlURL>
                        <eventSubURL>/upnp/control/wlanconfig1</eventSubURL>
                        <SCPDURL>/wlanconfigSCPD.xml</SCPDURL>
                    </service>
                    <!-- 1 -->
                    <service>
                        <serviceType>urn:dslforum-org:service:WLANConfiguration:2</serviceType>
                        <serviceId> urn:WLANConfiguration-com:serviceId:WLANConfiguration2 
                        </serviceId>
                        <controlURL>/upnp/control/wlanconfig2</controlURL>
                        <eventSubURL>/upnp/control/wlanconfig2</eventSubURL>
                        <SCPDURL>/wlanconfigSCPD.xml</SCPDURL>
                    </service>
                    <service>
                        <serviceType>urn:dslforum-org:service:Hosts:1</serviceType>
                        <serviceId>urn:LanDeviceHosts-com:serviceId:Hosts1</serviceId>
                        <controlURL>/upnp/control/hosts</controlURL>
                        <eventSubURL>/upnp/control/hosts</eventSubURL>
                        <SCPDURL>/hostsSCPD.xml</SCPDURL>
                    </service>
                    <service>
                        <serviceType> urn:dslforum-org:service:LANEthernetInterfaceConfig:1 
                        </serviceType>
                        <serviceId> urn:LANEthernetIfCfg-com:serviceId:LANEthernetInterfaceConfig1 
                        </serviceId>
                        <controlURL>/upnp/control/lanethernetifcfg</controlURL>
                        <eventSubURL>/upnp/control/lanethernetifcfg</eventSubURL>
                        <SCPDURL>/ethifconfigSCPD.xml</SCPDURL>
                    </service>
                    <service>
                        <serviceType>urn:dslforum-org:service:LANHostConfigManagement:1</serviceType>
                        <serviceId> urn:LANHCfgMgm-com:serviceId:LANHostConfigManagement1 
                        </serviceId>
                        <controlURL>/upnp/control/lanhostconfigmgm</controlURL>
                        <eventSubURL>/upnp/control/lanhostconfigmgm</eventSubURL>
                        <SCPDURL>/lanhostconfigmgmSCPD.xml</SCPDURL>
                    </service>
                </serviceList>
            </device>
            <device>
                <deviceType>urn:dslforum-org:device:WANDevice:1</deviceType>
                <friendlyName>WANDevice - FRITZ!Box 6360 Cable (um)</friendlyName>
                <manufacturer>AVM</manufacturer>
                <manufacturerURL>www.avm.de</manufacturerURL>
                <modelDescription>WANDevice - FRITZ!Box 6360 Cable (um)</modelDescription>
                <modelName>WANDevice - FRITZ!Box 6360 Cable (um)</modelName>
                <modelNumber>- unity</modelNumber>
                <modelURL>www.avm.de</modelURL>
                <UDN>uuid:CCCCC</UDN>
                <UPC>AVM TR-064</UPC>
                <serviceList>
                    <service>
                        <serviceType> urn:dslforum-org:service:WANCommonInterfaceConfig:1 
                        </serviceType>
                        <serviceId> urn:WANCIfConfig-com:serviceId:WANCommonInterfaceConfig1 
                        </serviceId>
                        <controlURL>/upnp/control/wancommonifconfig1</controlURL>
                        <eventSubURL>/upnp/control/wancommonifconfig1</eventSubURL>
                        <SCPDURL>/wancommonifconfigSCPD.xml</SCPDURL>
                    </service>
                    <service>
                        <serviceType>urn:dslforum-org:service:WANDSLInterfaceConfig:1</serviceType>
                        <serviceId> urn:WANDSLIfConfig-com:serviceId:WANDSLInterfaceConfig1 
                        </serviceId>
                        <controlURL>/upnp/control/wandslifconfig1</controlURL>
                        <eventSubURL>/upnp/control/wandslifconfig1</eventSubURL>
                        <SCPDURL>/wandslifconfigSCPD.xml</SCPDURL>
                    </service>
                </serviceList>
                <deviceList>
                    <device>
                        <deviceType>urn:dslforum-org:device:WANConnectionDevice:1</deviceType>
                        <friendlyName>WANConnectionDevice - FRITZ!Box 6360 Cable (um)</friendlyName>
                        <manufacturer>AVM</manufacturer>
                        <manufacturerURL>www.avm.de</manufacturerURL>
                        <modelDescription>WANConnectionDevice - FRITZ!Box 6360 Cable (um)</modelDescription>
                        <modelName>WANConnectionDevice - FRITZ!Box 6360 Cable (um)</modelName>
                        <modelNumber>- unity</modelNumber>
                        <modelURL>www.avm.de</modelURL>
                        <UDN>uuid:DDDDDDD</UDN>
                        <UPC>AVM TR-064</UPC>
                        <serviceList>
                            <service>
                                <serviceType>urn:dslforum-org:service:WANDSLLinkConfig:1</serviceType>
                                <serviceId> urn:WANDSLLinkConfig-com:serviceId:WANDSLLinkConfig1 
                                </serviceId>
                                <controlURL>/upnp/control/wandsllinkconfig1</controlURL>
                                <eventSubURL>/upnp/control/wandsllinkconfig1</eventSubURL>
                                <SCPDURL>/wandsllinkconfigSCPD.xml</SCPDURL>
                            </service>
                            <service>
                                <serviceType>urn:dslforum-org:service:WANEthernetLinkConfig:1</serviceType>
                                <serviceId> urn:WANEthernetLinkConfig-com:serviceId:WANEthernetLinkConfig1 
                                </serviceId>
                                <controlURL>/upnp/control/wanethlinkconfig1</controlURL>
                                <eventSubURL>/upnp/control/wanethlinkconfig1</eventSubURL>
                                <SCPDURL>/wanethlinkconfigSCPD.xml</SCPDURL>
                            </service>
                            <service>
                                <serviceType>urn:dslforum-org:service:WANPPPConnection:1</serviceType>
                                <serviceId> urn:WANPPPConnection-com:serviceId:WANPPPConnection1 
                                </serviceId>
                                <controlURL>/upnp/control/wanpppconn1</controlURL>
                                <eventSubURL>/upnp/control/wanpppconn1</eventSubURL>
                                <SCPDURL>/wanpppconnSCPD.xml</SCPDURL>
                            </service>
                            <service>
                                <serviceType>urn:dslforum-org:service:WANIPConnection:1</serviceType>
                                <serviceId>urn:WANIPConnection-com:serviceId:WANIPConnection1</serviceId>
                                <controlURL>/upnp/control/wanipconnection1</controlURL>
                                <eventSubURL>/upnp/control/wanipconnection1</eventSubURL>
                                <SCPDURL>/wanipconnSCPD.xml</SCPDURL>
                            </service>
                        </serviceList>
                    </device>
                </deviceList>
            </device>
        </deviceList>
        <presentationURL>http://fritz.box</presentationURL>
    </device>
</root>
```

**Comment by dampfnudel** [comment]
Point 2 and 3 are same.

fritzboxtr064:url=http://VALID_IP:49000

fritzboxtr064:user=custom_user
fritzboxtr064:pass=custom_password

**Comment by dampfnudel** [comment]
point is 1 is enabled.

**Comment by gitbock** [comment]
ok, your fbox provides all tr064 services properly. I expected that some differ from my reference implementation. But this is not the case; all required services are known.
I will consider to insert some more debug output while parsing the services in my next release.

**Comment by dampfnudel** [comment]
sure, please let me know once you have have a new release

Am Samstag, 31. Oktober 2015 schrieb gitbock :

**Comment by dampfnudel** [comment]
I just debugged into it. Please find the error below.

```
org.apache.http.conn.HttpHostConnectException: Connect to 192.168.1.32:49000 [/192.168.1.32] failed: Connection refused
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.openhab.binding.fritzboxtr064.internal.Tr064Comm.getFboxXmlResponse(Tr064Comm.java:761)
    at org.openhab.binding.fritzboxtr064.internal.Tr064Comm.readAllServices(Tr064Comm.java:555)
    at org.openhab.binding.fritzboxtr064.internal.Tr064Comm.init(Tr064Comm.java:145)
    at org.openhab.binding.fritzboxtr064.internal.Tr064Comm.<init>(Tr064Comm.java:100)
    at org.openhab.binding.fritzboxtr064.internal.FritzboxTr064Binding.activate(FritzboxTr064Binding.java:121)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
    at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
    at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
    at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
    at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
    at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
    at org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536)
    at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:260)
    at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
    at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
    at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
    at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
    at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
    ... 41 more
```

**Comment by gitbock** [comment]
Hmm... that does not make much sense to me. The error means that the fbox does not accept a connection on this port. But you already tested this successfully by running your manual test with the URL http://fritz.box:49000/tr64desc.xml

1) Did you try the manual URL test from the same machine as openhab is running on?

2) On your openhab machine use the following command to test if the connection is accepted

```
telnet <fbox ip> 49000
```

3) Are you aware of any firewall between your openhab host and the fritzbox? Port 49000 is not a common port and perhaps blocked by default.

**Comment by dampfnudel** [comment]
it is working now! I set it up from scratch and restarted everything again. Maybe this was fixing it.

Thanks for your effort.

**Comment by gitbock** [comment]
Great! I am glad it's working for you now :)

**Comment by schmidhorst** [comment]
At my FritzBox the "Fritz!App Ticker" App stopped working suddenly, remote access no more possible. The http://&lt;local-ip-of-fritzbox&gt;:49000/tr64desc.xml was still working, but the https://&lt;local-ip-of-fritzbox&gt;:49443/tr64desc.xml was refused. Also an https://&lt;publicIP&gt; (given e.g. under "Internet", "Freigaben", "Fritz!Box Dienste") was also not working. Restarting the box didn't help. The trouble was caused by my user certificate in the FritzBox. After a new load-up of my user certificate (or generating a new internal Certificate) it's now working again.

**Comment by gitbock** [comment]
@schmidhorst 
Thanks for sharing this with us! I will consider this as a wiki entry.
