### ISSUE TITLE
Unable to load addon with openhab2 2.0.0~b5

### ISSUE THREAD

**Issue by markussiebert** [gitbock/fritzboxtr064#24]
When trying to use this Plugin with openhab 2.0.0~b5 i get this errer:

`2017-01-13 11:10:30.589 [ERROR] [org.openhab.binding.fritzboxtr064   ] - FrameworkEvent ERROR - org.openhab.binding.fritzboxtr064
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.fritzboxtr064 [199]
  Unresolved requirement: Import-Package: org.openhab.core.binding
        at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
`

plugin was copied to /usr/share/openhab2/addons

**Comment by cirf** [comment]
Can also not load the plugin with openhab 2 final
