### ISSUE TITLE
Fritzbox 7490 with OS  06.83 seems to be broken

### ISSUE THREAD

**Issue by MrMontesa** [gitbock/fritzboxtr064#29]
I recently updated my fritz.box OS to  06.83. Since then tr064 Binding seems to not be able to parse fritzbox data any more.
My openhab.log contains lines like this:

```
2017-03-13 21:04:49.801 [ERROR] [ing.fritzboxtr064.internal.Tr064Comm] - Error received from FritzBox while parsing call list: <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:dslforum-org:control-1-0">
<errorCode>401</errorCode>
<errorDescription>invalid action</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>
2017-03-13 21:04:50.133 [INFO ] [tzboxtr064.internal.PhonebookManager] - Downloading phonebook ID 0
2017-03-13 21:04:50.155 [ERROR] [ing.fritzboxtr064.internal.Tr064Comm] - FritzBox returned unexpected response. Could not find expected datavalue NewPhonebookURL in response.
2017-03-13 21:04:50.158 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread FritzboxTr064 Refresh Service
java.lang.NullPointerException
        at java.net.URI$Parser.parse(URI.java:3042)[:1.8.0_111]
        at java.net.URI.<init>(URI.java:588)[:1.8.0_111]
        at java.net.URI.create(URI.java:850)[:1.8.0_111]
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)[250:org.openhab.binding.fritzboxtr064:1.9.0]
        at org.openhab.binding.fritzboxtr064.internal.Tr064Comm.getFboxXmlResponse(Tr064Comm.java:867)[250:org.openhab.binding.fritzboxtr064:1.9.0]
        at org.openhab.binding.fritzboxtr064.internal.PhonebookManager.downloadPhonebook(PhonebookManager.java:121)[250:org.openhab.binding.fritzboxtr064:1.9.0]
        at org.openhab.binding.fritzboxtr064.internal.PhonebookManager.downloadPhonebooks(PhonebookManager.java:133)[250:org.openhab.binding.fritzboxtr064:1.9.0]
        at org.openhab.binding.fritzboxtr064.internal.FritzboxTr064Binding.execute(FritzboxTr064Binding.java:154)[250:org.openhab.binding.fritzboxtr064:1.9.0]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:157)[176:org.openhab.core.compat1x:2.0.0]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)[176:org.openhab.core.compat1x:2.0.0]
```
Any suggestion on how to get tr064 Binding working again?
Thanks for your help.

**Comment by MrMontesa** [comment]
Found corresponding thread on [community forum](https://community.openhab.org/t/fritzbox-tr064-wan-ip/19634).
My best guess would be that AVM changes the UPnP reply message that tr064 binding is not aware of.
Let me know if I can be of any help getting this resolved. If I remeber correctly with the correct URL I might be able to poll the data via CURL to verify something has indeed changed.

**Comment by timtimsson** [comment]
:( i have thr same problem :(

**Comment by e36Alex** [comment]
got even the same problem.

**Comment by NCO3** [comment]
same here :-(

**Comment by bredmich** [comment]
Same problem here!
The Call Monitor and MAC-Online Features are still working fine.
But i can´t get the WAN-IP...

Same error:
```
2017-06-05 15:12:43.453 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - FritzBox returned unexpected response. Could not find expected datavalue NewExternalIPAddress in response <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:dslforum-org:control-1-0">
<errorCode>401</errorCode>
<errorDescription>Invalid Action</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>
```
